package com.lh.zksockets.data.DbDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lh.zksockets.data.model.ChazuoData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CHAZUO_DATA".
*/
public class ChazuoDataDao extends AbstractDao<ChazuoData, Long> {

    public static final String TABLENAME = "CHAZUO_DATA";

    /**
     * Properties of entity ChazuoData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property BindName = new Property(2, String.class, "bindName", false, "BIND_NAME");
        public final static Property IsOk = new Property(3, boolean.class, "isOk", false, "IS_OK");
        public final static Property OpenTime = new Property(4, int.class, "openTime", false, "OPEN_TIME");
        public final static Property ClosedTime = new Property(5, int.class, "closedTime", false, "CLOSED_TIME");
    }


    public ChazuoDataDao(DaoConfig config) {
        super(config);
    }
    
    public ChazuoDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CHAZUO_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"BIND_NAME\" TEXT," + // 2: bindName
                "\"IS_OK\" INTEGER NOT NULL ," + // 3: isOk
                "\"OPEN_TIME\" INTEGER NOT NULL ," + // 4: openTime
                "\"CLOSED_TIME\" INTEGER NOT NULL );"); // 5: closedTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CHAZUO_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ChazuoData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String bindName = entity.getBindName();
        if (bindName != null) {
            stmt.bindString(3, bindName);
        }
        stmt.bindLong(4, entity.getIsOk() ? 1L: 0L);
        stmt.bindLong(5, entity.getOpenTime());
        stmt.bindLong(6, entity.getClosedTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ChazuoData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String bindName = entity.getBindName();
        if (bindName != null) {
            stmt.bindString(3, bindName);
        }
        stmt.bindLong(4, entity.getIsOk() ? 1L: 0L);
        stmt.bindLong(5, entity.getOpenTime());
        stmt.bindLong(6, entity.getClosedTime());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ChazuoData readEntity(Cursor cursor, int offset) {
        ChazuoData entity = new ChazuoData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // bindName
            cursor.getShort(offset + 3) != 0, // isOk
            cursor.getInt(offset + 4), // openTime
            cursor.getInt(offset + 5) // closedTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ChazuoData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBindName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIsOk(cursor.getShort(offset + 3) != 0);
        entity.setOpenTime(cursor.getInt(offset + 4));
        entity.setClosedTime(cursor.getInt(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ChazuoData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ChazuoData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ChazuoData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
