package com.lh.zksockets.data.DbDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lh.zksockets.data.model.DangerOut;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DANGER_OUT".
*/
public class DangerOutDao extends AbstractDao<DangerOut, Long> {

    public static final String TABLENAME = "DANGER_OUT";

    /**
     * Properties of entity DangerOut.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DangerOut1 = new Property(1, int.class, "dangerOut1", false, "DANGER_OUT1");
        public final static Property DangerOut2 = new Property(2, int.class, "dangerOut2", false, "DANGER_OUT2");
        public final static Property DangerOut3 = new Property(3, int.class, "dangerOut3", false, "DANGER_OUT3");
        public final static Property DangerOut4 = new Property(4, int.class, "dangerOut4", false, "DANGER_OUT4");
    }


    public DangerOutDao(DaoConfig config) {
        super(config);
    }
    
    public DangerOutDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DANGER_OUT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"DANGER_OUT1\" INTEGER NOT NULL ," + // 1: dangerOut1
                "\"DANGER_OUT2\" INTEGER NOT NULL ," + // 2: dangerOut2
                "\"DANGER_OUT3\" INTEGER NOT NULL ," + // 3: dangerOut3
                "\"DANGER_OUT4\" INTEGER NOT NULL );"); // 4: dangerOut4
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DANGER_OUT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DangerOut entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getDangerOut1());
        stmt.bindLong(3, entity.getDangerOut2());
        stmt.bindLong(4, entity.getDangerOut3());
        stmt.bindLong(5, entity.getDangerOut4());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DangerOut entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getDangerOut1());
        stmt.bindLong(3, entity.getDangerOut2());
        stmt.bindLong(4, entity.getDangerOut3());
        stmt.bindLong(5, entity.getDangerOut4());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DangerOut readEntity(Cursor cursor, int offset) {
        DangerOut entity = new DangerOut( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // dangerOut1
            cursor.getInt(offset + 2), // dangerOut2
            cursor.getInt(offset + 3), // dangerOut3
            cursor.getInt(offset + 4) // dangerOut4
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DangerOut entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDangerOut1(cursor.getInt(offset + 1));
        entity.setDangerOut2(cursor.getInt(offset + 2));
        entity.setDangerOut3(cursor.getInt(offset + 3));
        entity.setDangerOut4(cursor.getInt(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DangerOut entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DangerOut entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DangerOut entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
