package com.lh.zksockets.data.DbDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lh.zksockets.data.model.Computer;
import com.lh.zksockets.data.model.IcCard;
import com.lh.zksockets.data.model.PowerDevice;
import com.lh.zksockets.data.model.Projector;
import com.lh.zksockets.data.model.Users;
import com.lh.zksockets.data.model.ChazuoData;

import com.lh.zksockets.data.DbDao.ComputerDao;
import com.lh.zksockets.data.DbDao.IcCardDao;
import com.lh.zksockets.data.DbDao.PowerDeviceDao;
import com.lh.zksockets.data.DbDao.ProjectorDao;
import com.lh.zksockets.data.DbDao.UsersDao;
import com.lh.zksockets.data.DbDao.ChazuoDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig computerDaoConfig;
    private final DaoConfig icCardDaoConfig;
    private final DaoConfig powerDeviceDaoConfig;
    private final DaoConfig projectorDaoConfig;
    private final DaoConfig usersDaoConfig;
    private final DaoConfig chazuoDataDaoConfig;

    private final ComputerDao computerDao;
    private final IcCardDao icCardDao;
    private final PowerDeviceDao powerDeviceDao;
    private final ProjectorDao projectorDao;
    private final UsersDao usersDao;
    private final ChazuoDataDao chazuoDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        computerDaoConfig = daoConfigMap.get(ComputerDao.class).clone();
        computerDaoConfig.initIdentityScope(type);

        icCardDaoConfig = daoConfigMap.get(IcCardDao.class).clone();
        icCardDaoConfig.initIdentityScope(type);

        powerDeviceDaoConfig = daoConfigMap.get(PowerDeviceDao.class).clone();
        powerDeviceDaoConfig.initIdentityScope(type);

        projectorDaoConfig = daoConfigMap.get(ProjectorDao.class).clone();
        projectorDaoConfig.initIdentityScope(type);

        usersDaoConfig = daoConfigMap.get(UsersDao.class).clone();
        usersDaoConfig.initIdentityScope(type);

        chazuoDataDaoConfig = daoConfigMap.get(ChazuoDataDao.class).clone();
        chazuoDataDaoConfig.initIdentityScope(type);

        computerDao = new ComputerDao(computerDaoConfig, this);
        icCardDao = new IcCardDao(icCardDaoConfig, this);
        powerDeviceDao = new PowerDeviceDao(powerDeviceDaoConfig, this);
        projectorDao = new ProjectorDao(projectorDaoConfig, this);
        usersDao = new UsersDao(usersDaoConfig, this);
        chazuoDataDao = new ChazuoDataDao(chazuoDataDaoConfig, this);

        registerDao(Computer.class, computerDao);
        registerDao(IcCard.class, icCardDao);
        registerDao(PowerDevice.class, powerDeviceDao);
        registerDao(Projector.class, projectorDao);
        registerDao(Users.class, usersDao);
        registerDao(ChazuoData.class, chazuoDataDao);
    }
    
    public void clear() {
        computerDaoConfig.clearIdentityScope();
        icCardDaoConfig.clearIdentityScope();
        powerDeviceDaoConfig.clearIdentityScope();
        projectorDaoConfig.clearIdentityScope();
        usersDaoConfig.clearIdentityScope();
        chazuoDataDaoConfig.clearIdentityScope();
    }

    public ComputerDao getComputerDao() {
        return computerDao;
    }

    public IcCardDao getIcCardDao() {
        return icCardDao;
    }

    public PowerDeviceDao getPowerDeviceDao() {
        return powerDeviceDao;
    }

    public ProjectorDao getProjectorDao() {
        return projectorDao;
    }

    public UsersDao getUsersDao() {
        return usersDao;
    }

    public ChazuoDataDao getChazuoDataDao() {
        return chazuoDataDao;
    }

}
