package com.lh.zksockets.data.DbDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lh.zksockets.data.model.DoorInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DOOR_INFO".
*/
public class DoorInfoDao extends AbstractDao<DoorInfo, Void> {

    public static final String TABLENAME = "DOOR_INFO";

    /**
     * Properties of entity DoorInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property IP = new Property(0, String.class, "IP", false, "IP");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property IsStart = new Property(2, int.class, "isStart", false, "IS_START");
    }


    public DoorInfoDao(DaoConfig config) {
        super(config);
    }
    
    public DoorInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DOOR_INFO\" (" + //
                "\"IP\" TEXT," + // 0: IP
                "\"NAME\" TEXT," + // 1: name
                "\"IS_START\" INTEGER NOT NULL );"); // 2: isStart
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DOOR_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DoorInfo entity) {
        stmt.clearBindings();
 
        String IP = entity.getIP();
        if (IP != null) {
            stmt.bindString(1, IP);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
        stmt.bindLong(3, entity.getIsStart());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DoorInfo entity) {
        stmt.clearBindings();
 
        String IP = entity.getIP();
        if (IP != null) {
            stmt.bindString(1, IP);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
        stmt.bindLong(3, entity.getIsStart());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public DoorInfo readEntity(Cursor cursor, int offset) {
        DoorInfo entity = new DoorInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // IP
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.getInt(offset + 2) // isStart
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DoorInfo entity, int offset) {
        entity.setIP(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setIsStart(cursor.getInt(offset + 2));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(DoorInfo entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(DoorInfo entity) {
        return null;
    }

    @Override
    public boolean hasKey(DoorInfo entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
