package com.lh.zksockets.data.DbDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lh.zksockets.data.model.IOYuan;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "IOYUAN".
*/
public class IOYuanDao extends AbstractDao<IOYuan, Long> {

    public static final String TABLENAME = "IOYUAN";

    /**
     * Properties of entity IOYuan.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DangerIo1 = new Property(1, int.class, "dangerIo1", false, "DANGER_IO1");
        public final static Property DangerIo2 = new Property(2, int.class, "dangerIo2", false, "DANGER_IO2");
        public final static Property DangerIo3 = new Property(3, int.class, "dangerIo3", false, "DANGER_IO3");
        public final static Property DangerIo4 = new Property(4, int.class, "dangerIo4", false, "DANGER_IO4");
    }


    public IOYuanDao(DaoConfig config) {
        super(config);
    }
    
    public IOYuanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"IOYUAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"DANGER_IO1\" INTEGER NOT NULL ," + // 1: dangerIo1
                "\"DANGER_IO2\" INTEGER NOT NULL ," + // 2: dangerIo2
                "\"DANGER_IO3\" INTEGER NOT NULL ," + // 3: dangerIo3
                "\"DANGER_IO4\" INTEGER NOT NULL );"); // 4: dangerIo4
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"IOYUAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, IOYuan entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getDangerIo1());
        stmt.bindLong(3, entity.getDangerIo2());
        stmt.bindLong(4, entity.getDangerIo3());
        stmt.bindLong(5, entity.getDangerIo4());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, IOYuan entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getDangerIo1());
        stmt.bindLong(3, entity.getDangerIo2());
        stmt.bindLong(4, entity.getDangerIo3());
        stmt.bindLong(5, entity.getDangerIo4());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public IOYuan readEntity(Cursor cursor, int offset) {
        IOYuan entity = new IOYuan( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // dangerIo1
            cursor.getInt(offset + 2), // dangerIo2
            cursor.getInt(offset + 3), // dangerIo3
            cursor.getInt(offset + 4) // dangerIo4
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, IOYuan entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDangerIo1(cursor.getInt(offset + 1));
        entity.setDangerIo2(cursor.getInt(offset + 2));
        entity.setDangerIo3(cursor.getInt(offset + 3));
        entity.setDangerIo4(cursor.getInt(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(IOYuan entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(IOYuan entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(IOYuan entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
