package com.lh.zksockets.data.DbDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lh.zksockets.data.model.PowerDevice;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "POWER_DEVICE".
*/
public class PowerDeviceDao extends AbstractDao<PowerDevice, Void> {

    public static final String TABLENAME = "POWER_DEVICE";

    /**
     * Properties of entity PowerDevice.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property DeviceName = new Property(0, String.class, "deviceName", false, "DEVICE_NAME");
        public final static Property OpenTime = new Property(1, int.class, "openTime", false, "OPEN_TIME");
        public final static Property ClosedTime = new Property(2, int.class, "closedTime", false, "CLOSED_TIME");
    }


    public PowerDeviceDao(DaoConfig config) {
        super(config);
    }
    
    public PowerDeviceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"POWER_DEVICE\" (" + //
                "\"DEVICE_NAME\" TEXT," + // 0: deviceName
                "\"OPEN_TIME\" INTEGER NOT NULL ," + // 1: openTime
                "\"CLOSED_TIME\" INTEGER NOT NULL );"); // 2: closedTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"POWER_DEVICE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PowerDevice entity) {
        stmt.clearBindings();
 
        String deviceName = entity.getDeviceName();
        if (deviceName != null) {
            stmt.bindString(1, deviceName);
        }
        stmt.bindLong(2, entity.getOpenTime());
        stmt.bindLong(3, entity.getClosedTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PowerDevice entity) {
        stmt.clearBindings();
 
        String deviceName = entity.getDeviceName();
        if (deviceName != null) {
            stmt.bindString(1, deviceName);
        }
        stmt.bindLong(2, entity.getOpenTime());
        stmt.bindLong(3, entity.getClosedTime());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public PowerDevice readEntity(Cursor cursor, int offset) {
        PowerDevice entity = new PowerDevice( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // deviceName
            cursor.getInt(offset + 1), // openTime
            cursor.getInt(offset + 2) // closedTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PowerDevice entity, int offset) {
        entity.setDeviceName(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setOpenTime(cursor.getInt(offset + 1));
        entity.setClosedTime(cursor.getInt(offset + 2));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(PowerDevice entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(PowerDevice entity) {
        return null;
    }

    @Override
    public boolean hasKey(PowerDevice entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
