package com.lh.zksockets.data.DbDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lh.zksockets.data.model.Projector;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PROJECTOR".
*/
public class ProjectorDao extends AbstractDao<Projector, Long> {

    public static final String TABLENAME = "PROJECTOR";

    /**
     * Properties of entity Projector.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property BaudRate = new Property(2, String.class, "baudRate", false, "BAUD_RATE");
        public final static Property BaudRateId = new Property(3, int.class, "baudRateId", false, "BAUD_RATE_ID");
        public final static Property CheckoutBit = new Property(4, String.class, "checkoutBit", false, "CHECKOUT_BIT");
        public final static Property CheckoutBitId = new Property(5, int.class, "checkoutBitId", false, "CHECKOUT_BIT_ID");
        public final static Property DataBit = new Property(6, String.class, "dataBit", false, "DATA_BIT");
        public final static Property DataBitId = new Property(7, int.class, "dataBitId", false, "DATA_BIT_ID");
        public final static Property StopBit = new Property(8, String.class, "stopBit", false, "STOP_BIT");
        public final static Property StopBitId = new Property(9, int.class, "stopBitId", false, "STOP_BIT_ID");
        public final static Property Type = new Property(10, String.class, "type", false, "TYPE");
        public final static Property TypeId = new Property(11, int.class, "typeId", false, "TYPE_ID");
        public final static Property OpenCommand = new Property(12, String.class, "openCommand", false, "OPEN_COMMAND");
        public final static Property ClosedCommand = new Property(13, String.class, "closedCommand", false, "CLOSED_COMMAND");
        public final static Property VGACommand = new Property(14, String.class, "VGACommand", false, "VGACOMMAND");
        public final static Property HDMICommand = new Property(15, String.class, "HDMICommand", false, "HDMICOMMAND");
        public final static Property JiChazuo = new Property(16, String.class, "jiChazuo", false, "JI_CHAZUO");
        public final static Property JiChazuoId = new Property(17, int.class, "jiChazuoId", false, "JI_CHAZUO_ID");
        public final static Property BuChazuo = new Property(18, String.class, "buChazuo", false, "BU_CHAZUO");
        public final static Property BuChazuoId = new Property(19, int.class, "buChazuoId", false, "BU_CHAZUO_ID");
    }


    public ProjectorDao(DaoConfig config) {
        super(config);
    }
    
    public ProjectorDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PROJECTOR\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"BAUD_RATE\" TEXT," + // 2: baudRate
                "\"BAUD_RATE_ID\" INTEGER NOT NULL ," + // 3: baudRateId
                "\"CHECKOUT_BIT\" TEXT," + // 4: checkoutBit
                "\"CHECKOUT_BIT_ID\" INTEGER NOT NULL ," + // 5: checkoutBitId
                "\"DATA_BIT\" TEXT," + // 6: dataBit
                "\"DATA_BIT_ID\" INTEGER NOT NULL ," + // 7: dataBitId
                "\"STOP_BIT\" TEXT," + // 8: stopBit
                "\"STOP_BIT_ID\" INTEGER NOT NULL ," + // 9: stopBitId
                "\"TYPE\" TEXT," + // 10: type
                "\"TYPE_ID\" INTEGER NOT NULL ," + // 11: typeId
                "\"OPEN_COMMAND\" TEXT," + // 12: openCommand
                "\"CLOSED_COMMAND\" TEXT," + // 13: closedCommand
                "\"VGACOMMAND\" TEXT," + // 14: VGACommand
                "\"HDMICOMMAND\" TEXT," + // 15: HDMICommand
                "\"JI_CHAZUO\" TEXT," + // 16: jiChazuo
                "\"JI_CHAZUO_ID\" INTEGER NOT NULL ," + // 17: jiChazuoId
                "\"BU_CHAZUO\" TEXT," + // 18: buChazuo
                "\"BU_CHAZUO_ID\" INTEGER NOT NULL );"); // 19: buChazuoId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PROJECTOR\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Projector entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String baudRate = entity.getBaudRate();
        if (baudRate != null) {
            stmt.bindString(3, baudRate);
        }
        stmt.bindLong(4, entity.getBaudRateId());
 
        String checkoutBit = entity.getCheckoutBit();
        if (checkoutBit != null) {
            stmt.bindString(5, checkoutBit);
        }
        stmt.bindLong(6, entity.getCheckoutBitId());
 
        String dataBit = entity.getDataBit();
        if (dataBit != null) {
            stmt.bindString(7, dataBit);
        }
        stmt.bindLong(8, entity.getDataBitId());
 
        String stopBit = entity.getStopBit();
        if (stopBit != null) {
            stmt.bindString(9, stopBit);
        }
        stmt.bindLong(10, entity.getStopBitId());
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(11, type);
        }
        stmt.bindLong(12, entity.getTypeId());
 
        String openCommand = entity.getOpenCommand();
        if (openCommand != null) {
            stmt.bindString(13, openCommand);
        }
 
        String closedCommand = entity.getClosedCommand();
        if (closedCommand != null) {
            stmt.bindString(14, closedCommand);
        }
 
        String VGACommand = entity.getVGACommand();
        if (VGACommand != null) {
            stmt.bindString(15, VGACommand);
        }
 
        String HDMICommand = entity.getHDMICommand();
        if (HDMICommand != null) {
            stmt.bindString(16, HDMICommand);
        }
 
        String jiChazuo = entity.getJiChazuo();
        if (jiChazuo != null) {
            stmt.bindString(17, jiChazuo);
        }
        stmt.bindLong(18, entity.getJiChazuoId());
 
        String buChazuo = entity.getBuChazuo();
        if (buChazuo != null) {
            stmt.bindString(19, buChazuo);
        }
        stmt.bindLong(20, entity.getBuChazuoId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Projector entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String baudRate = entity.getBaudRate();
        if (baudRate != null) {
            stmt.bindString(3, baudRate);
        }
        stmt.bindLong(4, entity.getBaudRateId());
 
        String checkoutBit = entity.getCheckoutBit();
        if (checkoutBit != null) {
            stmt.bindString(5, checkoutBit);
        }
        stmt.bindLong(6, entity.getCheckoutBitId());
 
        String dataBit = entity.getDataBit();
        if (dataBit != null) {
            stmt.bindString(7, dataBit);
        }
        stmt.bindLong(8, entity.getDataBitId());
 
        String stopBit = entity.getStopBit();
        if (stopBit != null) {
            stmt.bindString(9, stopBit);
        }
        stmt.bindLong(10, entity.getStopBitId());
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(11, type);
        }
        stmt.bindLong(12, entity.getTypeId());
 
        String openCommand = entity.getOpenCommand();
        if (openCommand != null) {
            stmt.bindString(13, openCommand);
        }
 
        String closedCommand = entity.getClosedCommand();
        if (closedCommand != null) {
            stmt.bindString(14, closedCommand);
        }
 
        String VGACommand = entity.getVGACommand();
        if (VGACommand != null) {
            stmt.bindString(15, VGACommand);
        }
 
        String HDMICommand = entity.getHDMICommand();
        if (HDMICommand != null) {
            stmt.bindString(16, HDMICommand);
        }
 
        String jiChazuo = entity.getJiChazuo();
        if (jiChazuo != null) {
            stmt.bindString(17, jiChazuo);
        }
        stmt.bindLong(18, entity.getJiChazuoId());
 
        String buChazuo = entity.getBuChazuo();
        if (buChazuo != null) {
            stmt.bindString(19, buChazuo);
        }
        stmt.bindLong(20, entity.getBuChazuoId());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Projector readEntity(Cursor cursor, int offset) {
        Projector entity = new Projector( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // baudRate
            cursor.getInt(offset + 3), // baudRateId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // checkoutBit
            cursor.getInt(offset + 5), // checkoutBitId
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // dataBit
            cursor.getInt(offset + 7), // dataBitId
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // stopBit
            cursor.getInt(offset + 9), // stopBitId
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // type
            cursor.getInt(offset + 11), // typeId
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // openCommand
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // closedCommand
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // VGACommand
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // HDMICommand
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // jiChazuo
            cursor.getInt(offset + 17), // jiChazuoId
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // buChazuo
            cursor.getInt(offset + 19) // buChazuoId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Projector entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBaudRate(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBaudRateId(cursor.getInt(offset + 3));
        entity.setCheckoutBit(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCheckoutBitId(cursor.getInt(offset + 5));
        entity.setDataBit(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setDataBitId(cursor.getInt(offset + 7));
        entity.setStopBit(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setStopBitId(cursor.getInt(offset + 9));
        entity.setType(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setTypeId(cursor.getInt(offset + 11));
        entity.setOpenCommand(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setClosedCommand(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setVGACommand(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setHDMICommand(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setJiChazuo(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setJiChazuoId(cursor.getInt(offset + 17));
        entity.setBuChazuo(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setBuChazuoId(cursor.getInt(offset + 19));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Projector entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Projector entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Projector entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
