package com.lh.zksockets.data.DbDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lh.zksockets.data.model.SerialPortData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SERIAL_PORT_DATA".
*/
public class SerialPortDataDao extends AbstractDao<SerialPortData, Long> {

    public static final String TABLENAME = "SERIAL_PORT_DATA";

    /**
     * Properties of entity SerialPortData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property SerialPortName = new Property(1, String.class, "serialPortName", false, "SERIAL_PORT_NAME");
        public final static Property BaudRate = new Property(2, String.class, "baudRate", false, "BAUD_RATE");
        public final static Property CheckoutBit = new Property(3, String.class, "checkoutBit", false, "CHECKOUT_BIT");
        public final static Property DataBit = new Property(4, String.class, "dataBit", false, "DATA_BIT");
        public final static Property StopBit = new Property(5, String.class, "stopBit", false, "STOP_BIT");
    }


    public SerialPortDataDao(DaoConfig config) {
        super(config);
    }
    
    public SerialPortDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SERIAL_PORT_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"SERIAL_PORT_NAME\" TEXT," + // 1: serialPortName
                "\"BAUD_RATE\" TEXT," + // 2: baudRate
                "\"CHECKOUT_BIT\" TEXT," + // 3: checkoutBit
                "\"DATA_BIT\" TEXT," + // 4: dataBit
                "\"STOP_BIT\" TEXT);"); // 5: stopBit
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SERIAL_PORT_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SerialPortData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String serialPortName = entity.getSerialPortName();
        if (serialPortName != null) {
            stmt.bindString(2, serialPortName);
        }
 
        String baudRate = entity.getBaudRate();
        if (baudRate != null) {
            stmt.bindString(3, baudRate);
        }
 
        String checkoutBit = entity.getCheckoutBit();
        if (checkoutBit != null) {
            stmt.bindString(4, checkoutBit);
        }
 
        String dataBit = entity.getDataBit();
        if (dataBit != null) {
            stmt.bindString(5, dataBit);
        }
 
        String stopBit = entity.getStopBit();
        if (stopBit != null) {
            stmt.bindString(6, stopBit);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SerialPortData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String serialPortName = entity.getSerialPortName();
        if (serialPortName != null) {
            stmt.bindString(2, serialPortName);
        }
 
        String baudRate = entity.getBaudRate();
        if (baudRate != null) {
            stmt.bindString(3, baudRate);
        }
 
        String checkoutBit = entity.getCheckoutBit();
        if (checkoutBit != null) {
            stmt.bindString(4, checkoutBit);
        }
 
        String dataBit = entity.getDataBit();
        if (dataBit != null) {
            stmt.bindString(5, dataBit);
        }
 
        String stopBit = entity.getStopBit();
        if (stopBit != null) {
            stmt.bindString(6, stopBit);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public SerialPortData readEntity(Cursor cursor, int offset) {
        SerialPortData entity = new SerialPortData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // serialPortName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // baudRate
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // checkoutBit
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // dataBit
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // stopBit
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SerialPortData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSerialPortName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBaudRate(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCheckoutBit(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDataBit(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setStopBit(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(SerialPortData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(SerialPortData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SerialPortData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
