package com.lh.zksockets.data.DbDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.lh.zksockets.data.model.VidStatus;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VID_STATUS".
*/
public class VidStatusDao extends AbstractDao<VidStatus, Long> {

    public static final String TABLENAME = "VID_STATUS";

    /**
     * Properties of entity VidStatus.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property VidinName = new Property(1, String.class, "vidinName", false, "VIDIN_NAME");
        public final static Property VidinStatus = new Property(2, String.class, "vidinStatus", false, "VIDIN_STATUS");
    }


    public VidStatusDao(DaoConfig config) {
        super(config);
    }
    
    public VidStatusDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VID_STATUS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"VIDIN_NAME\" TEXT," + // 1: vidinName
                "\"VIDIN_STATUS\" TEXT);"); // 2: vidinStatus
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VID_STATUS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, VidStatus entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String vidinName = entity.getVidinName();
        if (vidinName != null) {
            stmt.bindString(2, vidinName);
        }
 
        String vidinStatus = entity.getVidinStatus();
        if (vidinStatus != null) {
            stmt.bindString(3, vidinStatus);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, VidStatus entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String vidinName = entity.getVidinName();
        if (vidinName != null) {
            stmt.bindString(2, vidinName);
        }
 
        String vidinStatus = entity.getVidinStatus();
        if (vidinStatus != null) {
            stmt.bindString(3, vidinStatus);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public VidStatus readEntity(Cursor cursor, int offset) {
        VidStatus entity = new VidStatus( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // vidinName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // vidinStatus
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, VidStatus entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setVidinName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setVidinStatus(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(VidStatus entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(VidStatus entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(VidStatus entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
